import { NativeAd } from 'types/native-ad';

export const diffcheckerDesktopNativeAd: NativeAd = {
  platform: 'custom',
  active: '1',
  backgroundColor: 'transparent',
  backgroundHoverColor: 'transparent',
  company: 'Diffchecker Desktop',
  companyTagline: 'Diffchecker Desktop',
  callToAction: 'Get Desktop',
  ctaBackgroundColor: 'var(--theme-colors-background-green-primary-default)',
  ctaBackgroundHoverColor: 'var(--theme-colors-background-green-primary-hover)',
  ctaTextColor: 'var(--colors-white)',
  ctaTextColorHover: 'var(--colors-white)',
  description:
    'The most secure way to run Diffchecker. Get the Diffchecker Desktop app: your diffs never leave your computer!',
  evenodd: '0',
  height: '0',
  image: '/static/images/new/diffchecker.svg',
  rendering: 'default',
  statlink: `https://www.diffchecker.com/desktop`,
  textColor: '#00B3E6',
  textColorHover: '#00B3E6',
  title: '',
  disableNofollow: true,
  ourAd: true,
};

export const bibcitationNativeAd: NativeAd = {
  platform: 'custom',
  active: '1',
  backgroundColor: 'transparent',
  backgroundHoverColor: 'transparent',
  companyTagline: 'Bibcitation',
  callToAction: 'Check it out',
  company: 'Bibcitation',
  ctaBackgroundColor: 'var(--colors-purple-500)',
  ctaBackgroundHoverColor: 'var(--colors-purple-700)',
  ctaTextColor: 'var(--colors-white)',
  ctaTextColorHover: 'var(--colors-white)',
  description:
    'A free online tool to generate citations, reference lists, and bibliographies. APA, MLA, Chicago, and more.',
  evenodd: '0',
  height: '0',
  image: '/static/images/bibcitation.svg',
  rendering: 'default',
  statlink: 'https://www.bibcitation.com',
  textColor: '#8C4EF1',
  textColorHover: '#8C4EF1',
  title: '',
  disableNofollow: true,
  ourAd: true,
};

export const svgviewerNativeAd: NativeAd = {
  platform: 'custom',
  active: '1',
  backgroundColor: 'transparent',
  backgroundHoverColor: 'transparent',
  companyTagline: 'SVG Viewer',
  callToAction: 'Try it out',
  company: 'SVG Viewer',
  ctaBackgroundColor: 'var(--colors-orange-600)',
  ctaBackgroundHoverColor: 'var(--colors-orange-700)',
  ctaTextColor: 'var(--colors-white)',
  ctaTextColorHover: 'var(--colors-white)',
  description:
    'View, optimize, convert, and share your SVGs easily on the web! Also the most advanced icon search.',
  evenodd: '0',
  height: '0',
  image: '/static/images/svgviewer.svg',
  rendering: 'default',
  statlink: 'https://www.svgviewer.dev',
  textColor: '#00B3E6',
  textColorHover: '#00B3E6',
  title: '',
  disableNofollow: true,
  ourAd: true,
};

export const launchUiNativeAd: NativeAd = {
  platform: 'custom',
  active: '1',
  backgroundColor: 'transparent',
  backgroundHoverColor: 'transparent',
  callToAction: 'Check it out',
  company: 'Launch UI Components',
  ctaBackgroundColor: 'rgb(24, 24, 27)',
  companyTagline: 'Launch UI Components',
  ctaBackgroundHoverColor: 'rgb(24, 24, 27)',
  ctaTextColor: '#FFFFFF',
  ctaTextColorHover: '#FFFFFF',
  description:
    'Landing page components built with React, Shadcn/ui and Tailwind that will make your website feel premium.',
  evenodd: '0',
  height: '0',
  image: 'https://www.svgviewer.dev/images/launch-ui.png',
  rendering: 'default',
  statlink: `https://www.launchuicomponents.com`,
  title: '',
  textColor: '#00B3E6',
  textColorHover: '#00B3E6',
  disableNofollow: true,
};

export const defaultGoogleAd: NativeAd = {
  platform: 'google',
  active: '1',
  backgroundColor: 'transparent',
  backgroundHoverColor: 'transparent',
  company: 'Google Ad',
  companyTagline: 'Google Ad',
  callToAction: 'Learn More',
  ctaBackgroundColor: '#4285F4',
  ctaBackgroundHoverColor: '#3367D6',
  ctaTextColor: '#FFFFFF',
  ctaTextColorHover: '#FFFFFF',
  description: 'This is a placeholder for a Google Ad.',
  evenodd: '0',
  height: '0',
  image: '/static/images/google-ad-placeholder.svg',
  rendering: 'default',
  statlink: 'https://www.google.com/ads',
  textColor: '#000000',
  textColorHover: '#000000',
  title: 'Google Advertisement',
  disableNofollow: false,
  ourAd: false,
};
